name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      # Install latest Terraform manually as
      #  Docker-based GitHub Actions are
      #  slow due to lack of caching
      # Note: Terraform is not needed for tflint
      - name: Install Terraform
        run: |
          brew install terraform

      # Run init to get module code to be able to use `--module`
      - name: Terraform init
        working-directory: ./terraform
        run: |
          terraform init

      # Run TFLint
      - name: tflint with reviewdog output on the PR
        uses: reviewdog/action-tflint@46e609666b039b775a150e84781ef79ea90089a8 # tag=v1.17.0
        with:
          working-directory: ./terraform

  # -- SECURITY ---------------------------------------------------------------
  tfsec:
    name: runner / tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      # Run TFSec
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@1f6d9e763be79aed3128bc23efaead45d7e11430 # tag=v1.14.4
        with:
          working-directory: ./terraform
