name: Code Review

on: [pull_request]

jobs:

  # -- LINT -------------------------------------------------------------------
  tflint:
    name: TFLint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      # Install latest Terraform manually as
      #  Docker-based GitHub Actions are
      #  slow due to lack of caching
      # Note: Terraform is not needed for tflint
      - name: Install Terraform
        run: |
          brew install terraform

      # Run init to get module code to be able to use `--module`
      - name: Terraform init
        working-directory: ./terraform
        run: |
          terraform init

      # Run TFLint
      - name: tflint with reviewdog output on the PR
        uses: reviewdog/action-tflint@9e5d83f1ae29d6b967aea785b84b7927a4b64ff7 # tag=v1.17.1
        with:
          working-directory: ./terraform

  # -- SECURITY ---------------------------------------------------------------
  tfsec:
    name: TFSec
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@5e53a6998f4b1305aa150682211e74ec0d8d2dda
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      # Run TFSec
      - name: Run tfsec with reviewdog output on the PR
        uses: reviewdog/action-tfsec@c33e075b53fed70183e46124801ff934b5c5ff8b # tag=v1.15.2
        with:
          working-directory: ./terraform
